First part of bash CLI task
chernokoz/bashSimpleInterpreter pull request #1
Opened 2020-08-19 16:57 UTC by chernokoz

2020-08-20 19:55 UTC, yurii-litvinov requested changes
Надо ещё CI настроить. Ещё стоит сдделать так, чтобы оно запускалось из консоли, для этого можно воспользоваться gradle application plugin, например. Ещё по условию требовалось "немного текста, описывающего детали реализации", в дополнение к диаграмме (например, в README.md можно вставить картинку с диаграммой и написать абзац текста про то, как всё работает). И автоматически сгенерированная диаграмма на самом деле не очень полезна, тем более что в ней нет информации о связях кроме наследования.

Ещё подстановка вида
```
x=ex
y=it
$x$y
``` 
не работает (падает при попытке создать процесс, должна отработать как встроенная команда exit)

```
wc build.gradle
```
выдаёт `1 1 32`, что, видимо, неправда (возможно, тоже из-за переводов строк, как и тесты --- я под Windows запускал), на pwd никак не реагирует

`cat .gitignore | |` падает, пытаясь создать процесс, а по-хорошему, должно адекватно ругаться на незаконченный пайп. И падать при создании процесса тоже не надо, не запустился --- ну и ладно, продолжаем работу.

Поправьте, пожалуйста.

2020-08-20 19:55 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/Command.java
> +    String in = null;
Поля с пакетной видимостью --- это нарушение инкапсуляции, тем более что у Вас всё в одном пакете, так что это равносильно паблик-видимости. Кстати, неплохо бы навести некоторую иерархичность пакетов, хотя бы команды вынести в отдельный пакет

2020-08-20 19:55 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/Command.java
> +    ArrayList<String> arguments = null;
Лучше просто List<string> --- dependency inversion principle, один из принципов SOLID, минимизируйте зависимости от конкретных классов.

2020-08-20 19:55 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/CommandCat.java
> +public class CommandCat extends Command {
Тут по-хорошему тоже надо комментарий, и вообще всем классам и их паблик-методам (кроме оверрайдов)

2020-08-20 19:55 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/CommandCat.java
> +            StringJoiner res = new StringJoiner("\n");
А тут, кстати, лучше var (тип очевиден из правой части присваивания), но поскольку это дело вкуса, можно не править

2020-08-20 19:55 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/CommandExit.java
> +            throw new ExitException("fd");
Почему fd?

2020-08-20 19:55 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/OutsideCommand.java
> +        builder.command("/bin/bash", "-c", commandString);
Думаю, что под Windows это работать не будет, а программа должна быть максимально кроссплатформенна. Благо в Java есть вполне кроссплатформенное API для запуска процессов и запускать шелл только для того, чтобы в нём запустить процесс, может быть плохой идеей.

2020-08-20 19:55 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/Parser.java
> +                Token identifier = sequenceTokenList.get(i+1);
`i + 1`, пробелов не хватает

2020-08-20 19:55 UTC, yurii-litvinov commented on src/test/java/com/chernokoz/MainTest.java
> +        assertEquals("exit: too many arguments\n", testFunc("echo 123 | exit 123 456"));
Под Windows тесты не проходят, из-за разницы в переводах строк (под виндой `\r\n`)

2020-09-05 10:34 UTC, chernokoz commented on src/main/java/com/chernokoz/Command.java
> +    String in = null;
Поправил видимость, создал иерархичность пакетов

2020-09-05 10:34 UTC, chernokoz commented on src/main/java/com/chernokoz/Command.java
> +    ArrayList<String> arguments = null;
Поправил!

2020-09-05 10:34 UTC, chernokoz commented on src/main/java/com/chernokoz/CommandCat.java
> +public class CommandCat extends Command {
Добавил!

2020-09-05 10:35 UTC, chernokoz commented on src/main/java/com/chernokoz/CommandExit.java
> +            throw new ExitException("fd");
Поправил!

2020-09-05 10:36 UTC, chernokoz commented on src/main/java/com/chernokoz/CommandCat.java
> +            StringJoiner res = new StringJoiner("\n");
В джаве привык всегда прописывать тип. Попробовал Котлин впервые вот когда писали roguelike - понравилось использовать var и val.

2020-09-05 10:38 UTC, chernokoz commented on src/main/java/com/chernokoz/OutsideCommand.java
> +        builder.command("/bin/bash", "-c", commandString);
Поправил разделением логики для платформ, но не совсем понял про кроссплатформенное API, в Windows же cmd.

2020-09-05 10:39 UTC, chernokoz commented on src/test/java/com/chernokoz/MainTest.java
> +        assertEquals("exit: too many arguments\n", testFunc("echo 123 | exit 123 456"));
Поправил все моменты с \r\n, подтянул репозиторий на ПК с windows, потестил, вроде теперь все работает.

2020-09-05 10:43 UTC, chernokoz commented
`Надо ещё CI настроить. Ещё стоит сдделать так, чтобы оно запускалось из консоли, для этого можно воспользоваться gradle application plugin, например. Ещё по условию требовалось "немного текста, описывающего детали реализации", в дополнение к диаграмме (например, в README.md можно вставить картинку с диаграммой и написать абзац текста про то, как всё работает). И автоматически сгенерированная диаграмма на самом деле не очень полезна, тем более что в ней нет информации о связях кроме наследования.
`
CI настроил, gradle application plugin настроил, но все равно не очень понял, почему-то не работает так как хотелось бы.

```
Ещё подстановка вида

x=ex
y=it
$x$y
не работает (падает при попытке создать процесс, должна отработать как встроенная команда exit)
```
Поправил! Теперь работает.

```
wc build.gradle
выдаёт 1 1 32, что, видимо, неправда (возможно, тоже из-за переводов строк, как и тесты --- я под Windows запускал), на pwd никак не реагирует
```
Поправил, там логика неправильная была получения содержимого файла

`cat .gitignore | | падает, пытаясь создать процесс, а по-хорошему, должно адекватно ругаться на незаконченный пайп. И падать при создании процесса тоже не надо, не запустился --- ну и ладно, продолжаем работу.`

Поправил, теперь поведение как в баше.

2020-09-06 10:28 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/OutsideCommand.java
> +        builder.command("/bin/bash", "-c", commandString);
Тут я имел в виду, что можно просто ProcessBuilder-ом, вовссе не обязательно для запуска внешнего процесса использовать шелл. На самом деле, часто это оверкилл, особенно если запускать шелл **только** для того, чтобы запустить в нём процесс. Да, шелл умнее (например, там алиасы есть), но тут мы же сами типа пишем шелл, отсутствие всяких quality-of-life-фич вполне ожидаемо.

2020-09-06 11:58 UTC, yurii-litvinov requested changes
- Не показывается stderr запущенных внешних процессов. Попробуйте git ololo, например
- Ещё было бы неплохо добавлять перевод строки после вывода предыдущей команды
- Совсем ничего не говорить при неудачном запуске процесса тоже неправильно (думаю, что это связано с отсутствием поддержки stderr и запуском через шелл, впрочем, но неплохо бы поправить)

В общем, надо ещё немного поправить

2020-09-06 11:58 UTC, yurii-litvinov commented on .travis.yml
> +  - ./gradlew test
В принципе, на travis есть предустановленный gradle, и если пользоваться им, можно сэкономить некоторое время билда за счёт того, что gradle не будет качаться при каждой сборке.

2020-09-06 11:58 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/Main.java
> +//import com.chernokoz.exceptions.CommandNotFoundException;
Закомментированный код не нужен :)

2020-09-06 11:58 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/Main.java
> +        Lexer lexer = new Lexer(str);
Тут тоже var-ы бы лучше смотрелись, на мой вкус

2020-09-06 11:58 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/Main.java
> +        System.out.print("[ Shell != Neste ] -> ");
Приглашение ко вводу печатается после выхода из шелла? :)

2020-09-06 11:58 UTC, yurii-litvinov commented on build.gradle
> +}
Чтобы работало как надо, надо дописать
```
run {
    standardInput = System.in
}
```

2020-09-07 23:21 UTC, chernokoz commented on .travis.yml
> +  - ./gradlew test
Попробовал, но, к сожалению, это не мой вариант. Только новый gradle поддерживает java 14, поэтому предустановленный не билдит проект. Но буду знать, спасибо!

2020-09-07 23:22 UTC, chernokoz commented on src/main/java/com/chernokoz/Main.java
> +//import com.chernokoz.exceptions.CommandNotFoundException;
Поправил.

2020-09-07 23:22 UTC, chernokoz commented on src/main/java/com/chernokoz/Main.java
> +        Lexer lexer = new Lexer(str);
Ну я в этом месте кода для пробы поменял)

2020-09-07 23:22 UTC, chernokoz commented on src/main/java/com/chernokoz/Main.java
> +        System.out.print("[ Shell != Neste ] -> ");
Поправил.

2020-09-07 23:25 UTC, chernokoz commented on build.gradle
> +}
Дописал, но суть не в этом была.

Долго пришлось гуглить, чтобы понять в чем проблема.
Там есть rich console, status bar которого выводился прямо на печатаемых командах. По дефолту в терминале macos он был включен. Я нашел запускать без него и добавил в README.md:

gradle --console=plain run

2020-09-07 23:28 UTC, chernokoz commented
> Не показывается stderr запущенных внешних процессов. Попробуйте git ololo, например
Добавил логику с stderr, теперь git ololo отрабатывает как надо.

> Ещё было бы неплохо добавлять перевод строки после вывода предыдущей команды
Да, логично - добавил!

> Совсем ничего не говорить при неудачном запуске процесса тоже неправильно (думаю, что это связано с отсутствием поддержки stderr и запуском через шелл, впрочем, но неплохо бы поправить)
Теперь правильно работает не только git ololo, но и неудачные запуски процессов!

2020-09-09 17:02 UTC, yurii-litvinov commented on .travis.yml
> +  - ./gradlew test
Я вот тоже подумал, что, скорее всего, gradle там староват, но потом подумал, что JDK 14 Вы ж используете готовый :) Надеюсь, что образ на travis обновят рано или поздно

2020-09-09 17:03 UTC, yurii-litvinov commented on build.gradle
> +}
Ага, я с `--console=plain` запускал

2020-09-09 17:07 UTC, yurii-litvinov approved these changes
Да, теперь всё круто, зачтена

2020-09-10 11:32 UTC, merged