CLI grep
chernokoz/bashSimpleInterpreter pull request #3
Opened 2020-09-08 11:34 UTC by chernokoz

Один коммит получился из-за того, что я уже написал этот код давно в другой ветке, ответвленной от старой версии part1. Чтобы наложить их уже на свежую версию part1, я скопировал код в новую(от свежей версии part1) ветку.

По выбору библиотеки: рассматривал 3 варианта:

- Apache Commons CLI
- args4j (когда смотрел ее github репозиторий, понял что автор - создатель Jenkins.)
- picocli

По функциональности подходили все, но у Apache Commons CLI более стандартный синтаксис - создаем опции, создаем парсер и добавляем опции в список опций парсера, а потом запускаем, в то время как у args4j и picocli похожий синтаксис с использованием аннотаций, для лучшей читабельности кода решил выбирать из них. Сначала попытался внедрить args4j, не получалось заставить работать, почитал про использование picocli(они похожи) и понял, что там удобнее. В picocli можно создать отдельный класс с опциями и аргументами и его передавать в объект CommandLine, а в args4j они описываются в том же классе. В итоге перешел на picocli, так как там легче разносить логику, да и заработало сразу - более дружелюбная документация(пример использования в ней).

2020-09-09 18:43 UTC, yurii-litvinov requested changes
На некорректном вводе (`grep -A pattern`, например) падает. А должно бы не падать и ругаться на отрицательный аргумент в -A. Поправьте, пожалуйста.

2020-09-09 18:43 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/commands/CommandGrep.java
> +                result.add(runGrep(Collections.singletonList(content)));
Collections.singletonList немутабелен, поэтому оно падает на https://github.com/chernokoz/bashSimpleInterpreter/pull/3/commits/ad043d713a8dc495e7da3e68ce85e6ff5d36cbad#diff-a9c328c64b58da03b742af2333208350R109 при попытке считать из файла

2020-09-09 18:43 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/commands/CommandGrep.java
> +    int keyAValue = 0;
Им правда нужна пакетная видимость?

2020-09-09 18:43 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/exceptions/PatternNotFoundException.java
> +public class PatternNotFoundException extends Exception {}
По-хорошему, исключениям тоже нужен комментарий

2020-09-10 16:13 UTC, chernokoz commented
> На некорректном вводе (`grep -A pattern`, например) падает. А должно бы не падать и ругаться на отрицательный аргумент в -A. Поправьте, пожалуйста.

Поправил!

2020-09-10 16:14 UTC, chernokoz commented on src/main/java/com/chernokoz/exceptions/PatternNotFoundException.java
> +public class PatternNotFoundException extends Exception {}
Добавил.

2020-09-10 16:14 UTC, chernokoz commented on src/main/java/com/chernokoz/commands/CommandGrep.java
> +    int keyAValue = 0;
Ошибка, поправил.

2020-09-10 16:15 UTC, chernokoz commented on src/main/java/com/chernokoz/commands/CommandGrep.java
> +                result.add(runGrep(Collections.singletonList(content)));
Да, поправил, теперь с файлами, передаваемыми в аргументах, работает корректно.

2020-09-12 18:36 UTC, yurii-litvinov approved these changes
На отрицательный  аргумент в -A всё ещё не ругается (`grep -A -1 plugin build.gradle` спокойно выдаёт `plugins {`), но всё остальное теперь правильно, зачтена

2020-09-12 18:36 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/commands/CommandGrep.java
> +                String [] content = new String(Files.readAllBytes(Paths.get(fileName))).split(System.lineSeparator());
Несколько нетрадиционно пробел перед []

2020-09-12 18:36 UTC, yurii-litvinov commented on src/main/java/com/chernokoz/commands/CommandGrep.java
> +    private String grepHelper(String [] lines, String pattern) {
Кстати, и тут, так что это, видимо, не просто опечатка :)

2020-09-20 16:33 UTC, merged