Магазин книг
chernokoz/bashSimpleInterpreter pull request #4
Opened 2020-09-11 21:08 UTC by chernokoz

2020-09-13 09:19 UTC, yurii-litvinov requested changes
- Ещё желательно исходник диаграммы приложить
- Ассоциации и атрибуты не должны дублировать друг друга. Например, Book имеет поле category типа Category и ассоциацию с классом Category. По синтаксису UML это означает, что у Book аж два поля типа Category
- Зато User и Book ассоциацией не связаны, а у User есть поле типа `List<Book>`. Я б поле убрал, а ассоциацию со множественностью * добавил. Вообще, диаграмме явно не хватает связей.
- Book и Category вряд ли связаны композицией. По диаграмме получается, что если мы удаляем книгу, то и категория удаляется. То же с автором, OrderElement и т.д. Проверьте. Закрашенный ромбик означает, что тот, с чьей он стороны, владеет объектом, и при удалении хозяина удалится и сам объект. Незакрашенный ромбик --- что объект имеет ссылку на объект, но на время жизни никак не влияет.
- Cart, наверное, создаёт Order (`<<create>>`)
- Вообще, не стоит повсюду Id-шники добавлять, это ж концептуальная модель. При реализации разберутся, а сейчас незачем диаграмму деталями реализации загромождать.
- Кстати, `elements: List<OrderElement>` на UML пишется как `elements: OrderElement [*]`. UML ничего не знает про List-ы, зато знает про множественность. Но я бы лучше ассоциации со множественностью нарисовал, они более визуальны, чем поля.
- Оплату я бы не стал реализовывать как просто методы у Order --- а вдруг новые методы оплаты добавятся? Лучше сделать новую иерархию классов, а Order чтобы знал только про интерфейс оплаты.
- Веб-сервис вроде как требовался в ТЗ, но по диаграмме совсем непонятно, что торчит наружу как веб-сервис, а что нет. Стоит следать отдельный класс для веб-сервиса.
- Заказ напрямую не связан с пользователем, так что как его отменить, непонятно. Да, наверное, найти в базе по Id, но в этом и смысл концептуальной модели, чтобы визуализировать все связи, которые потом будут хитро реализованы через Id, репозитории и т.п.
- Функциональность поиска не раскрыта (а тут есть где развернуться, например, паттерном "Спецификация")
- Делать ревью одним классом не очень хорошо с точки зрения ООП, потому что они бывают пользовательские и редакторские, и обладают разными свойствами (то есть в одном случае будут заполнены одни поля, в другом другие).

2020-09-15 01:02 UTC, chernokoz commented
> * Ещё желательно исходник диаграммы приложить
> * Ассоциации и атрибуты не должны дублировать друг друга. Например, Book имеет поле category типа Category и ассоциацию с классом Category. По синтаксису UML это означает, что у Book аж два поля типа Category
> * Зато User и Book ассоциацией не связаны, а у User есть поле типа `List<Book>`. Я б поле убрал, а ассоциацию со множественностью * добавил. Вообще, диаграмме явно не хватает связей.
> * Book и Category вряд ли связаны композицией. По диаграмме получается, что если мы удаляем книгу, то и категория удаляется. То же с автором, OrderElement и т.д. Проверьте. Закрашенный ромбик означает, что тот, с чьей он стороны, владеет объектом, и при удалении хозяина удалится и сам объект. Незакрашенный ромбик --- что объект имеет ссылку на объект, но на время жизни никак не влияет.
> * Cart, наверное, создаёт Order (`<<create>>`)
> * Вообще, не стоит повсюду Id-шники добавлять, это ж концептуальная модель. При реализации разберутся, а сейчас незачем диаграмму деталями реализации загромождать.
> * Кстати, `elements: List<OrderElement>` на UML пишется как `elements: OrderElement [*]`. UML ничего не знает про List-ы, зато знает про множественность. Но я бы лучше ассоциации со множественностью нарисовал, они более визуальны, чем поля.
> * Оплату я бы не стал реализовывать как просто методы у Order --- а вдруг новые методы оплаты добавятся? Лучше сделать новую иерархию классов, а Order чтобы знал только про интерфейс оплаты.
> * Веб-сервис вроде как требовался в ТЗ, но по диаграмме совсем непонятно, что торчит наружу как веб-сервис, а что нет. Стоит следать отдельный класс для веб-сервиса.
> * Заказ напрямую не связан с пользователем, так что как его отменить, непонятно. Да, наверное, найти в базе по Id, но в этом и смысл концептуальной модели, чтобы визуализировать все связи, которые потом будут хитро реализованы через Id, репозитории и т.п.
> * Функциональность поиска не раскрыта (а тут есть где развернуться, например, паттерном "Спецификация")
> * Делать ревью одним классом не очень хорошо с точки зрения ООП, потому что они бывают пользовательские и редакторские, и обладают разными свойствами (то есть в одном случае будут заполнены одни поля, в другом другие).

Спасибо за подробные пояснения что не так, в целом со всем согласен, все поправил. Веб-сервис единственное не очень понятно как правильно делать, я просто создал отдельный класс с json обработчиком.  По поводу паттерна "спецификация" - добавил отдельный класс спецификации книги, через который уже будет легко реализовывать комбинирование фильтров.

2020-09-16 11:27 UTC, yurii-litvinov requested changes
- А всё равно поля и ассоциации дублируются, например, Category и Book. То же в Cart и разных Review.
- Оплате может требоваться дополнительная информация, просто pay(value) может быть недостаточно подробно. Может, имело смысл указать, что оно User принимает или даже способы оплаты связаны с User-ом (например, именно там хранится номер счёта каждого конкретного пользователя или что-то такое). Это действительно архитектурное решение --- системы оплаты как сервисы, принимающие информацию об оплате от пользователя, или как классы с состоянием, которые знают про всё, что надо для оплаты, и умеют собственно выполнять транзакцию.
- Review и RedactorReview могли быть в одной иерархии наследования от абстрактного ревью, они всё-таки имеют схожие свойства. Кстати, поле с содержимым ревью называется test, что странно :)
- Веб-сервис в виде класса Connector лучше, чем ничего (хотя там опечатка в названии метода), но ещё лучше было бы предоставить более высокоуровневые методы, типа getBooksList, searchBook, getUsers и т.п. Можно какие-то ключевые методы, позволяющие базовую работу с магазином, указать, типа возможности получить список книг и заказать книгу.
- BookSpecification точно в отношении композиции с Shop? Просто непонятно, зачем его вообще хранить --- нам дают поисковый запрос, мы его парсим в дерево спецификаций (или просто в объект-спецификацию, смотря насколько крутой Вы видите поисковую систему), исполняем относительно каталога, выдаём результаты, выкидываем спецификации. Это, скорее, зависимость вида `<<use>>` или `<<create>>`. 

Доисправляйте, пожалуйста.

2020-09-16 14:10 UTC, chernokoz commented
> * А всё равно поля и ассоциации дублируются, например, Category и Book. То же в Cart и разных Review.

Поправил.

> * Оплате может требоваться дополнительная информация, просто pay(value) может быть недостаточно подробно. Может, имело смысл указать, что оно User принимает или даже способы оплаты связаны с User-ом (например, именно там хранится номер счёта каждого конкретного пользователя или что-то такое). Это действительно архитектурное решение --- системы оплаты как сервисы, принимающие информацию об оплате от пользователя, или как классы с состоянием, которые знают про всё, что надо для оплаты, и умеют собственно выполнять транзакцию.

Да, поправил, теперь Pay знает про пользователя, но правда интерфейс пришлось сделать абстрактным классом.

> * Review и RedactorReview могли быть в одной иерархии наследования от абстрактного ревью, они всё-таки имеют схожие свойства. Кстати, поле с содержимым ревью называется test, что странно :)

Так и сделал, опечатку поправил.

> * Веб-сервис в виде класса Connector лучше, чем ничего (хотя там опечатка в названии метода), но ещё лучше было бы предоставить более высокоуровневые методы, типа getBooksList, searchBook, getUsers и т.п. Можно какие-то ключевые методы, позволяющие базовую работу с магазином, указать, типа возможности получить список книг и заказать книгу.

Добавил методы, просто их в общем случае может быть очень много, это меня и смутило.

> * BookSpecification точно в отношении композиции с Shop? Просто непонятно, зачем его вообще хранить --- нам дают поисковый запрос, мы его парсим в дерево спецификаций (или просто в объект-спецификацию, смотря насколько крутой Вы видите поисковую систему), исполняем относительно каталога, выдаём результаты, выкидываем спецификации. Это, скорее, зависимость вида `<<use>>` или `<<create>>`.

Да, тут конечно не нужно хранить BookSpecification, поменял отношение на <<use>>.

2020-09-16 14:42 UTC, yurii-litvinov approved these changes
Так и всё равно Cart содержит поле User, и UserReview тоже :) Но в целом всё хорошо, так что зачтена

2020-09-16 16:19 UTC, chernokoz commented
Спасибо, а у меня же вроде уже хватает задач на зачет?

2020-09-20 16:35 UTC, closed without merging